#!/usr/bin/env bash
# Install AgentOS status hooks for the four supported harnesses.
#
# Idempotent: safe to run on every container start. Each harness's config is
# merged rather than overwritten, so a user's own hooks, MCP servers and
# settings survive.

set -euo pipefail

HOOK_DIR="${AGENTOS_HOOK_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/hooks" && pwd)}"
STATUS="$HOOK_DIR/agentos-status.sh"
CODEX_NOTIFY="$HOOK_DIR/agentos-codex-notify.sh"

chmod +x "$STATUS" "$CODEX_NOTIFY" 2>/dev/null || true
mkdir -p "${AGENTOS_STATUS_DIR:-$HOME/.agent-os/status}"

# ── Claude Code and Command Code ──────────────────────────────────────────
# Command Code is a Claude Code fork and uses the same hook system, just
# under its own config directory.
#
# The events chosen map cleanly onto the three states worth showing:
#   UserPromptSubmit / PreToolUse -> running
#   Notification                  -> waiting (it fires for permission and
#                                    needs-input prompts)
#   Stop                          -> done
#   SessionEnd                    -> idle
install_claude_style() {
    local config_dir="$1" label="$2"
    local settings="$config_dir/settings.json"

    mkdir -p "$config_dir"
    [ -f "$settings" ] || echo '{}' > "$settings"

    STATUS="$STATUS" LABEL="$label" node -e '
const fs = require("fs");
const path = process.argv[1];
const status = process.env.STATUS;
const label = process.env.LABEL;

let settings = {};
try {
  settings = JSON.parse(fs.readFileSync(path, "utf8")) || {};
} catch {
  // Unparseable settings: start from empty rather than throwing away a
  // file we cannot understand. The write below is what replaces it.
  settings = {};
}

settings.hooks = settings.hooks || {};

const entry = (state) => ({
  hooks: [{ type: "command", command: `${status} ${state} ${label}` }],
});

// Replace only our own entries, keyed by the script path, so hooks the
// user added by hand are left alone.
const mine = (h) =>
  JSON.stringify(h).includes("agentos-status.sh");

for (const [event, state] of [
  ["UserPromptSubmit", "running"],
  ["PreToolUse", "running"],
  ["Notification", "waiting"],
  ["Stop", "done"],
  ["SessionEnd", "idle"],
]) {
  const existing = (settings.hooks[event] || []).filter((h) => !mine(h));
  settings.hooks[event] = [...existing, entry(state)];
}

fs.writeFileSync(path, JSON.stringify(settings, null, 2) + "\n");
' "$settings"

    echo "hooks: $label -> $settings"
}

install_claude_style "$HOME/.claude" claude
install_claude_style "$HOME/.commandcode" commandcode

# Claude Code profile clones share the binary but not the config dir.
for profile in a b c; do
    [ -d "$HOME/.claude-profiles/$profile" ] || continue
    install_claude_style "$HOME/.claude-profiles/$profile" "claude-$profile"
done

# ── Codex ─────────────────────────────────────────────────────────────────
# Codex supports a single event, agent-turn-complete, so it can report
# "done" and nothing else. Its config is TOML, and `notify` is a top-level
# array, so append it only when absent rather than rewriting the file.
CODEX_CONFIG="$HOME/.codex/config.toml"
mkdir -p "$HOME/.codex"
touch "$CODEX_CONFIG"

if grep -q '^notify' "$CODEX_CONFIG" 2>/dev/null; then
    echo "hooks: codex -> $CODEX_CONFIG (notify already set, left alone)"
else
    printf '\n# AgentOS terminal status\nnotify = ["%s"]\n' "$CODEX_NOTIFY" >> "$CODEX_CONFIG"
    echo "hooks: codex -> $CODEX_CONFIG"
fi

# ── OpenCode ──────────────────────────────────────────────────────────────
# OpenCode loads plugins from its config directory. session.idle gives us
# "done"; permission.ask gives "waiting" on versions where it fires.
OPENCODE_PLUGIN_DIR="$HOME/.config/opencode/plugin"
mkdir -p "$OPENCODE_PLUGIN_DIR"

cat > "$OPENCODE_PLUGIN_DIR/agentos-status.js" <<'PLUGIN'
// AgentOS terminal status reporter.
//
// Generated by scripts/install-agent-hooks.sh - edits will be overwritten.
import { execFile } from "child_process";

// Absolute path baked in at install time: the plugin runs inside OpenCode,
// which does not inherit AgentOS's environment.
const STATUS = "__AGENTOS_STATUS_HOOK__";

function report(state) {
  execFile(STATUS, [state, "opencode"], () => {});
}

export const AgentOSStatus = async () => ({
  event: async ({ event }) => {
    if (event?.type === "session.idle") report("done");
    if (event?.type === "session.error") report("idle");
  },
  "permission.ask": async () => {
    report("waiting");
  },
});
PLUGIN

sed -i "s|__AGENTOS_STATUS_HOOK__|$STATUS|" "$OPENCODE_PLUGIN_DIR/agentos-status.js"

echo "hooks: opencode -> $OPENCODE_PLUGIN_DIR/agentos-status.js"
echo "AgentOS status hooks installed."
